import { Poppins } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
})

export const metadata = {
  title: "Authantication",
  description: "Generated by create next app",
  icons: {
    icon:'/assets/security.svg'
  }
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${poppins.className} flex  justify-center bg-gray-800 items-center sm:mt-5`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
